# -*- coding: utf-8 -*-
"""Irys_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OCvkeoWsFmLHMn8lImJuzG-QxJ7uHNLs
"""

# Instalacja
!pip install -q tensorflow opencv-python pillow

# Import bibliotek - URUCHOM TO NAJPIERW!
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
import matplotlib.pyplot as plt
import numpy as np
import os
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
from google.colab import files
import shutil

print(f"TensorFlow: {tf.__version__}")

print("Wybierz 20 plików: setosa1.jpg ... setosa20.jpg")
uploaded = files.upload()
os.makedirs('dataset/setosa', exist_ok=True)
for filename in uploaded.keys():
    shutil.move(filename, f'dataset/setosa/{filename}')
print(f"Wgrano {len(uploaded)} zdjęć setosa")

print("Wybierz 20 plików: versicolor1.jpg ... versicolor20.jpg")
uploaded = files.upload()
os.makedirs('dataset/versicolor', exist_ok=True)
for filename in uploaded.keys():
    shutil.move(filename, f'dataset/versicolor/{filename}')
print(f"Wgrano {len(uploaded)} zdjęć versicolor")

print("Wybierz 20 plików: virginica1.jpg ... virginica20.jpg")
uploaded = files.upload()
os.makedirs('dataset/virginica', exist_ok=True)
for filename in uploaded.keys():
    shutil.move(filename, f'dataset/virginica/{filename}')
print(f"✅ Wgrano {len(uploaded)} zdjęć virginica")

IMG_SIZE = 150

from sklearn.model_selection import train_test_split

def split_dataset(source_dir, train_dir, test_dir, test_size=0.2):
 """Dzieli dataset na train/test zachowując strukturę katalogów"""
 for class_name in os.listdir(source_dir):
  class_path = os.path.join(source_dir, class_name)
  if not os.path.isdir(class_path):
   continue

  images = [f for f in os.listdir(class_path) if f.endswith(('.jpg',
'.jpeg', '.png'))]
  train_imgs, test_imgs = train_test_split(images, test_size=test_size, random_state=42)

  os.makedirs(f'{train_dir}/{class_name}', exist_ok=True)
  os.makedirs(f'{test_dir}/{class_name}', exist_ok=True)

  for img in train_imgs:
   shutil.copy(f'{class_path}/{img}', f'{train_dir}/{class_name}/{img}')
  for img in test_imgs:
   shutil.copy(f'{class_path}/{img}', f'{test_dir}/{class_name}/{img}')

  print(f"✅ Train: {len(train_imgs)*3} | Test: {len(test_imgs)*3}")

split_dataset('dataset', 'dataset_split/train', 'dataset_split/test')

# Augmentacja dla treningu
train_datagen = ImageDataGenerator(
 rescale=1./255,
 rotation_range=40,
 width_shift_range=0.2,
 height_shift_range=0.2,
 shear_range=0.2,
 zoom_range=0.2,
 horizontal_flip=True,
 fill_mode='nearest'
)

# Tylko normalizacja dla testu
test_datagen = ImageDataGenerator(rescale=1./255)

# Wczytanie danych
train_generator = train_datagen.flow_from_directory(
 'dataset_split/train',
 target_size=(IMG_SIZE, IMG_SIZE),
 batch_size=16,
 class_mode='categorical'
)

test_generator = test_datagen.flow_from_directory(
 'dataset_split/test',
 target_size=(IMG_SIZE, IMG_SIZE),
 batch_size=16,
 class_mode='categorical',
 shuffle=False
)

class_names = list(train_generator.class_indices.keys())
print(f"\nKlasy: {class_names}")
print(f"Train samples: {train_generator.samples}")
print(f"Test samples: {test_generator.samples}")

plt.figure(figsize=(12, 8))
for i in range(9):
 plt.subplot(3, 3, i+1)
 img_batch, label_batch = next(train_generator)
 plt.imshow(img_batch[0])
 plt.title(class_names[np.argmax(label_batch[0])])
 plt.axis('off')
plt.tight_layout()
plt.show()

from tensorflow import keras

model = keras.Sequential([
 # Block 1
 layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
 layers.MaxPooling2D((2, 2)),

 # Block 2
 layers.Conv2D(64, (3, 3), activation='relu'),
 layers.MaxPooling2D((2, 2)),

 # Block 3
 layers.Conv2D(128, (3, 3), activation='relu'),
 layers.MaxPooling2D((2, 2)),

 # Classifier
 layers.Flatten(),
 layers.Dropout(0.5),
 layers.Dense(128, activation='relu'),
 layers.Dropout(0.3),
 layers.Dense(3, activation='softmax')
])

# Kompilacja
model.compile(
 optimizer='adam',
 loss='categorical_crossentropy',
 metrics=['accuracy']
)

# Podsumowanie
model.summary()

# Callbacks
early_stop = keras.callbacks.EarlyStopping(
 monitor='val_loss',
 patience=5,
 restore_best_weights=True
)

reduce_lr = keras.callbacks.ReduceLROnPlateau(
 monitor='val_loss',
 factor=0.5,
 patience=3,
 min_lr=1e-7
)

# Trenowanie
history = model.fit(
 train_generator,
 epochs=30,
 validation_data=test_generator,
 callbacks=[early_stop, reduce_lr]
)

print("\nTrenowanie zakończone!")

plt.figure(figsize=(14, 5))

# Accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Val')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Accuracy')

# Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train')
plt.plot(history.history['val_loss'], label='Val')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('Loss')

plt.tight_layout()
plt.show()

# Ewaluacja
test_generator.reset()
test_loss, test_acc = model.evaluate(test_generator)
print(f"\nTest Accuracy: {test_acc:.4f} ({test_acc*100:.2f}%)")
print(f"Test Loss: {test_loss:.4f}")

# Predykcja
test_generator.reset()
y_pred = model.predict(test_generator)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = test_generator.classes

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred_classes)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
 xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Classification Report
print(classification_report(y_true, y_pred_classes, target_names=class_names))

import requests
from io import BytesIO
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array

def predict_flower(image_path):
 img = load_img(image_path, target_size=(IMG_SIZE, IMG_SIZE))
 img_array = img_to_array(img) / 255.0
 img_array = np.expand_dims(img_array, axis=0)

 predictions = model.predict(img_array, verbose=0)
 predicted_idx = np.argmax(predictions[0])
 predicted_class = class_names[predicted_idx]
 confidence = predictions[0][predicted_idx] * 100

 plt.figure(figsize=(10, 4))
 plt.subplot(1, 2, 1)
 plt.imshow(img)
 plt.title(f"{predicted_class} ({confidence:.1f}%)", fontweight='bold')
 plt.axis('off')

 plt.subplot(1, 2, 2)
 colors = ['green' if i == predicted_idx else 'lightblue' for i in range(3)]
 plt.barh(class_names, predictions[0] * 100, color=colors)
 plt.xlabel('Prawdopodobieństwo (%)')
 plt.xlim(0, 100)
 plt.tight_layout()
 plt.show()

 return predicted_class, confidence

url = "https://i.ibb.co/CmLc0tX/Iris-versicolor-3.jpg" # Updated to a direct image link
response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})

print(f"Content-Type: {response.headers.get('Content-Type')}")
print(f"Content Start (first 100 bytes): {response.content[:100]}")

img = Image.open(BytesIO(response.content))
img = img.convert('RGB') # Convert image to RGB mode before saving as JPEG
img.save('/tmp/test.jpg')
predict_flower('/tmp/test.jpg')